SET C51INC=C:\Keil_v5\C51\Inc;C:\Keil_v5\C51\Inc\Atmel
SET C51LIB=C:\Keil_v5\C51\Lib
SET CPU_TYPE=AT89S52
SET CPU_VENDOR=Atmel
SET UV2_TARGET=Target 1
SET CPU_XTAL=0x01F78A40
"C:\Keil_v5\C51\BIN\A51.EXE" @".\Objects\STARTUP._ia"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\delay.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\ExternalInterrupt0.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\Interrupt.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\Serial.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\SerialBase.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\T2_Delay.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\TimeCounter0.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\Timer2.__i"
"C:\Keil_v5\C51\BIN\C51.EXE" @".\Objects\Timer2_PWM.__i"
"C:\Keil_v5\C51\BIN\LIB51.EXE" @"".\Objects\51lib.__b""
